# This config.yml file is for Starport 
# Reference: https://docs.starport.network/kb/config.html
#
accounts:
  - name: alice
    coins: ["2000000000000stake","1000000000000000denom1","1000000000000000denom2"]
  - name: bob # auctioneer
    coins: ["2000000000000stake","1000000000000000denom1"]
  - name: steve # bidder
    coins: ["1000000000000000denom2"]
validator:
  name: alice
  staked: "1000000000000stake"
client:
  openapi:
    path: "client/docs/static/openapi.yml"
faucet:
  name: alice
  coins: ["100000stake", "1000000denom1", "1000000denom2"]
